name: rotabot
source_path: cmd/app

allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc
  - mpl-2.0

# Any dependencies that cannot be vetted by `licensed` and that you have
# manually vetted can be added to the list below.
reviewed:
  go:
    - golang.org/**/*