openapi: 3.0.3
info:
    title: Rotabot Service
    description: SlackApp that makes team rotations easy
    version: "1.0"
servers:
    - url: http://localhost:8000
paths:
    /:
        get:
            tags:
                - Rotabot
            summary: Home Rotabot
            operationId: Rotabot#Home
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quisquam nam consequatur et pariatur.
                            example: Cum maiores ut omnis qui voluptatem.
    /healthcheck:
        get:
            tags:
                - Rotabot
            summary: Healthcheck Rotabot
            operationId: Rotabot#Healthcheck
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Ipsa et.
                            example: Magni aut sed.
components: {}
tags:
    - name: Rotabot
      description: Service responsible for handling commands to create, update, and manage rotas
